### ISSUE TITLE
Does this disable Intel if my laptop runs on GPU by default?

### ISSUE THREAD

**Issue by saif-ellafi** [wildtruc/nvidia-prime-select#16]
Hi, On Fedora 30, after NVIDIA driver installation, my laptop is always on GPU. I read this library helps if the discrete video card is OFF by default and we turn it ON.

**Comment by wildtruc** [comment]
This probably a Fedora Nvidia driver management issue. nvidia-prime doesn't disable intel in anyway.
If the intel is disable, it come probably from bios.

**Comment by saif-ellafi** [comment]
on my laptop the discrete GPU is always on by default. Ubuntu's prime select can disable it by system reboot, bumblebee works well on demand however performance is awful.

Was looking for something making it work on demand just like Windows, no luck

**Comment by wildtruc** [comment]
that bummblebee does (on demand), sadly project is mostly dead.
May be it's a good alternative idea to test 'offload' if you have a recent laptop that support 440 serie driver (see README file).
This not include in NPS yet as default because it need some local test and my laptop isn't supported 440 driver serie.
