### ISSUE TITLE
turn off Nvidia on the run.

### ISSUE THREAD

**Issue by takov751** [wildtruc/nvidia-prime-select#8]
I see that you haven't implanted bbswitch in this script. May i ask the reason behind it? And i use hardcoded prime and i use intel driver instead of modesetting every  xorg configuration is the same. I opened this issue as a discussion .Sorry in advance if it was pointless/inapropriate.

**Comment by wildtruc** [comment]
Don't be. :)
The script doesn't use bbswitch because nvidia-drm is dedicated to PRIME and turn on the nvidia discrete card when loaded. That's it.
You can still use bbswitch, however, when using PRIME (and not Primus) nvidia discrete card is use a main graphic card and you don't have to constantly turn it off like bumblebleed or primus do.

For diff between intel driver and modesetting, I did use too in older distribution kernels, but it finally just stop too work with new distro upgrade. Modesetting is now the best alternative until a new better one.

Maybe in a near future, with nvidia-drm driver enhancements, config and switch will become different, but at this point, this is the only one we get.

I hope having answered to you question. Cheers!
